### ISSUE TITLE
VisualPaginator jako komponenta?

### ISSUE THREAD

**Issue by JanSuchanek** [mrtnzlml/www.zeminem.cz#19]
Proč stránkovadlo nemáš jako továrničku?

AdminPresenter:

	protected function createComponentPaginator()
	{
		return $this->visualPaginatorFactory->create(25);
		//$vp = $this->visualPaginatorFactory->create();
		//$vp->setItemsPerPage(25);
		//return $vp;		
	}
	public function renderPictures() {
		$paginator = $this['paginator']->getPaginator();
		$paginator->itemCount = $this->pictures->countBy();
		$this->template->pictures = $this->pictures->findBy(
			[], 
			['created' => 'DESC'], 
			$paginator->itemsPerPage, 
			$paginator->offset
		);
	}

**Comment by mrtnzlml** [comment]
Nevím... :)

Předpokládám, že to nemá žádný hlubší význam a prostě jsem to nakopíroval. Quick 'n' dirty. Ono obecně ten kód bych chtěl už hodně obnovit podle současných trendů, protože se tato struktura aplikace táhne z dob dávných a dneska už je takto nepíšu. Ale už to tak bývá, že když to funguje, tak mě nic moc netlačí s tím něco dělat a raději pracuji s tím jak to je. Až se k tomu někdy dostanu, tak to můžu předělat...

**Comment by JanSuchanek** [comment]
OK, jasný já furt po sobě přepisuji je to nekonečný :( No refresh tvého blogu na novou verzi by se hodil začátečníkům s Nette+Doctrine a samozřejmě i mě a hlavně Nette, vypiš akci na $ příspěvky, rád na vývoj přispěji (pokud budeš mít time a chuť).

**Comment by mrtnzlml** [comment]
To ne... :) Když to někoho zajímá, tak to udělám tak jako tak. Ono se toho zase tolik nezmění, spíš to chce trošku jinou strukturu aplikace a vyřešit tyto naprasené věci. Teď dělám ve firmě na jednom zajímavém projektu a když to bude dobré, tak bych to rád přemigroval právě na toto lepší jádro. No, ještě uvidím. Dej tomu nějaký čas. Jen tak to nebude...

**Comment by JanSuchanek** [comment]
:+1: Kdyby byl zájem o úpravy tak klidně pošlu pull nejen kosmetických změn tak pošlu třeba se nějaký časem povedou :)

**Comment by mrtnzlml** [comment]
Pokud chceš tak klidně, nebráním se tomu... :)

**Comment by JanSuchanek** [comment]
Ok když se nepoužije nevadí aspoň se něco naučím :+1:
