### ISSUE TITLE
Add an open-source licence, please?

### ISSUE THREAD

**Issue by enumag** [mrtnzlml/www.zeminem.cz#25]
I'd like to create my own blog but I couldn't find any time to implement it myself for the last two years. So I might as well use an existing solution and yours is a good one (even though it does not use doctrine).

Would you be willing to add an open-source licence to this project so that I can actually use it? I not, I understand. I can find a different solution.

**Comment by mrtnzlml** [comment]
No problem. What about same licence as Nette Framework? It's **BSD-3-Clause** or **GPL-2.0** or **GPL-3.0**. Would this be ok?

And btw. Why do you think it does not use Doctrine? I know that the usage of Doctrine in this case is not perfect (historical reasons), but it is actually using [Doctrine only](https://github.com/mrtnzlml/www.zeminem.cz/blob/develop/app/config/config.local.neon.dist#L8-10)...

**Comment by enumag** [comment]
Oops, I'm sorry I was thinking about several things at once. Don't know why I wrote Doctrine. You don't use nextras/secured-links which means potential CSRF vulnerabilities.

BSD-3-Clause should be fine, thanks! :+1:

**Comment by mrtnzlml** [comment]
Ok, licence added.

I have no problem to add another feature, but to be honest I have no idea what is it actually doing. Is there some kind of doc or literature (article, ...)? Potential vulnerability doesn't sound very scientific and it's not in framework itself. So I'd like to read something about it.

**Comment by enumag** [comment]
Thanks for the licence. :-)

Well it seems it has no documentation. First read something about what CSRF is if you don't know (czech wikipedia should be enough to understand the basics: https://cs.wikipedia.org/wiki/Cross-site_request_forgery). Then think about signals in your app, for example `AdminPresenter::handleDelete($id)` - it is vulnerable to this kind of attack. Now nextras/secured-links provides you with an easy way to solve it. All you need to do is use a trait in your presenter and add a `@secured` annotation to the signal you want.

This vulnerability can of course apply to actions as well, but nextras does not solve that. For this reason I always use a very simple convention - all database inserts/updates/deletes should be done by signals, not actions (submitting a form is a signal). This is actually one of the things I might write about on the blog some day.

**Comment by mrtnzlml** [comment]
Yeah, I know CSRF, but I don't know how does this nextras library behaves with wrong security token in URL and so on. It's very important for me. And I am still wondering why it's not implemented in Nette. It's actually pretty simple, because every CSRF protection has some cons...

Very simple solution should be to use some kind of multiplied form with CSRF protection enabled for delete (and another similar) handlers. And it's without magic.

I am going to close this issue and open another one for CSRF protection only.

**Comment by enumag** [comment]
Invalid token = BadSignalException = error 403 (https://github.com/nette/application/blob/master/src/Application/UI/BadSignalException.php). You can change the behaviour in ErrorPresenter of course.

As for nette read [this topic](https://goo.gl/YIc7zN).

**Comment by mrtnzlml** [comment]
Ok, 403 is not that bad. Make sense.

The issue confirms it's not a good idea to use it this way. But you're right, it should be secured and I am working on it. But it's not that easy because of Kdyby\AOP. Stay tuned... :)
